name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install deps and build (with cache)
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run format

      - name: Test
        run: yarn run test

      - name: Build
        run:  yarn run build
